#!/usr/bin/env python3
"""Builds the 4 program pages from ONE shared layout.

    python3 _src/program-pages/build.py      (run from the repo root)

Writes:
  marketing-programs/{local-seo,spark,expand,conquer}/index.html
  css/program.<hash>.css   (base.css + program.css, content-hashed like the
                            other shared sheets; old program.*.css removed)

Header, mobile nav, footer, analytics and theme scripts are copied from the
homepage (index.html, the header 51 pages share) at build time, so the
program pages match the rest of the site. Checkout buttons carry
data-checkout / data-period and get their Stripe links from
/js/program-checkout.js, the same file the pricing cards use.

_src/ is in .vercelignore: none of this is deployed, only its output.
"""
import glob, hashlib, html, json, os, re

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
SRC = os.path.dirname(os.path.abspath(__file__))
ORIGIN = 'https://www.outworkemdigital.com'
BRAND = "Outwork'em Digital"

def rd(p): return open(os.path.join(ROOT, p), encoding='utf-8').read()

# ---------------------------------------------------------------- shared CSS
css = open(os.path.join(SRC, 'base.css')).read() + '\n' + open(os.path.join(SRC, 'program.css')).read()
h = hashlib.sha1(css.encode()).hexdigest()[:10]
for old in glob.glob(os.path.join(ROOT, 'css', 'program.*.css')): os.remove(old)
CSS_HREF = f'/css/program.{h}.css'
open(os.path.join(ROOT, CSS_HREF.lstrip('/')), 'w').write(
    "/* Shared stylesheet for the 4 program pages (/marketing-programs/<plan>/).\n"
    "   Generated by _src/program-pages/build.py; edit the sources there. */\n" + css)

# ------------------------------------------------------- chrome from homepage
home = rd('index.html')
ANALYTICS = home[home.index('<script>'):home.index('</script>') + 9]
FONTS = '\n'.join(l for l in home.split('\n') if l.startswith('<link') and 'fonts.g' in l)
THEME = re.search(r'<script>\s*/\* Dark is the default.*?</script>', home, re.S).group(0)
ICONS = '\n'.join(l for l in home.split('\n') if l.startswith('<link rel="icon"') or l.startswith('<link rel="apple-touch-icon"'))
BODY_TOP = re.sub(r' class="current"', '', home[home.index('<body>') + 6:home.index('<main id="main">')])
FOOTER = home[home.index('<footer'):home.index('</footer>') + 9]
assert 'mobileNav' in BODY_TOP and '<header>' in BODY_TOP and 'site-footer' in FOOTER

# --------------------------------------------------------------- program data
PROGRAMS = {
  'local-seo': dict(name='Local SEO + Google Business Profile', short='Local SEO', kind='Local SEO plan',
    price='$350', mo='$350/mo', yr='$3,780/yr', yr_mo='$315/mo', yr_total='$3,780', yr_month='$315',
    offer=(350, 3780, False), spots=None, featured=False),
  'spark': dict(name='Spark Growth', short='Spark', kind='Growth program', price='$2,500', mo='$2,500/mo',
    yr='$27,000/yr', yr_mo='$2,250/mo', yr_total='$27,000', yr_month='$2,250', offer=(2500, 27000, False),
    spots='2 Spots Available', featured=False, channels=1),
  'expand': dict(name='Expand Growth', short='Expand', kind='Growth program', price='$3,500', mo='$3,500/mo',
    yr='$37,800/yr', yr_mo='$3,150/mo', yr_total='$37,800', yr_month='$3,150', offer=(3500, 37800, False),
    spots='2 Spots Available', featured=True, channels=2),
  'conquer': dict(name='Conquer Growth', short='Conquer', kind='Growth program', price='$4,500+', mo='$4,500+/mo',
    yr='$48,600+/yr', yr_mo='$4,050+/mo', yr_total='$48,600+', yr_month='$4,050+', offer=(4500, 48600, True),
    spots='1 Spot Available', featured=False, channels=3),
}
ORDER = ['local-seo', 'spark', 'expand', 'conquer']

CHANNEL_LABEL = {1: '1 Ad Channel of Your Choice (Google, Meta, or ChatGPT)',
                 2: '2 Ad Channels of Your Choice (Google, Meta, or ChatGPT)',
                 3: 'All 3 Ad Channels (Google, Meta, and ChatGPT)'}   # = the card wording
GROWTH_LIST = ['Custom Website Design', 'Search Engine Optimization', 'Reputation Management', 'Google Local Services Ads']

PAGES = {
  'local-seo': dict(
    title="Local SEO + Google Business Profile | Outwork'em Digital",
    desc="Local SEO from $350/month: we manage your Google Business Profile and give your website a light review and light updates. Month-to-month, 30 days' notice.",
    h1='Local SEO + Google Business Profile Plan',
    summary='Google Business Profile management plus a light website review and light website updates, for home service contractors who want to start with the basics.',
  ),
  'spark': dict(
    title="Spark Growth Program, $2,500/mo | Outwork'em Digital",
    desc="Spark Growth, $2,500/month: a custom website, SEO, reputation management, Google Local Services Ads and 1 ad channel of your choice. Month-to-month.",
    h1='Spark Growth Program for Home Service Contractors',
    summary='A custom website, SEO, reputation management and Google Local Services Ads, plus 1 ad channel of your choice: Google, Meta or ChatGPT.',
  ),
  'expand': dict(
    title="Expand Growth Program, $3,500/mo | Outwork'em Digital",
    desc="Expand Growth, $3,500/month: a custom website, SEO, reputation management, Google Local Services Ads and 2 ad channels of your choice. Our most popular plan.",
    h1='Expand Growth Program for Home Service Contractors',
    summary='A custom website, SEO, reputation management and Google Local Services Ads, plus 2 ad channels of your choice: Google, Meta or ChatGPT.',
  ),
  'conquer': dict(
    title="Conquer Growth Program, $4,500+/mo | Outwork'em Digital",
    desc="Conquer Growth, from $4,500/month: a custom website, SEO, reputation management, Google Local Services Ads and all 3 ad channels: Google, Meta and ChatGPT.",
    h1='Conquer Growth Program for Home Service Contractors',
    summary='A custom website, SEO, reputation management and Google Local Services Ads, with ads on all 3 channels: Google, Meta and ChatGPT.',
  ),
}

# What's included. Every sentence is drawn from an existing page; the source is
# noted next to each block.
INC_WEBSITE = dict(icon='web', title='Custom website design', paras=[
  # website-design-services "What's Included" + process; marketing-programs "Website Foundation"
  'We design and build a custom website for your business, tailored to your brand and built mobile-first on a proven WordPress framework. It includes a homepage that builds trust and turns visitors into leads, service pages that rank for profitable keywords, service area pages for hyper-local searches, and about and team pages.',
  # website-design-services; marketing-programs "Full ownership of your website"
  'Every site gets on-page SEO and schema markup, Core Web Vitals optimization, lead capture forms and click-to-call. You review and approve at every stage, and you keep full ownership of your website.'],
  more=('/marketing-services/website-design-services/', 'More about website design'))
INC_SEO = dict(icon='search', title='Search engine optimization', paras=[
  # organic-seo-services hero, revenue cards, timeline; marketing-programs "Content Marketing"
  'SEO helps homeowners find you on Google, Bing and other search engines without paying for every click. We handle the technical optimization and schema markup on your site and build out content for the installs, repairs and service calls you want more of.',
  # marketing-programs "Local SEO", "Listing Management", "Complete Google Business Profile optimization"; organic-seo timeline lead
  'Local SEO is part of it: we optimize your Google Business Profile and manage your listings so you show up in &#8220;near me&#8221; searches and the Google Map Pack. SEO builds lasting authority that keeps delivering leads long after the work is done, unlike paid ads that stop the moment you stop paying.'],
  more=('/marketing-services/organic-seo-services/', 'More about organic SEO'))
INC_REP = dict(icon='star_rate', title='Reputation management', paras=[
  # reputation-management-services FAQ 03
  'After each completed job, the system sends your customer a timed text and email with a simple one-tap link to leave a review, when satisfaction is at its highest. It runs on autopilot, so your team doesn&#8217;t have to remember to ask.',
  # reputation-management-services pillars
  'We monitor your reviews across platforms in one dashboard, with real-time alerts, and write professional, on-brand responses, including to negative reviews. Your best reviews are showcased on your website, and review schema markup helps them show up as star snippets in search.'],
  more=('/marketing-services/reputation-management-services/', 'More about reputation management'))
INC_LSA = dict(icon='storefront', title='Google Local Services Ads', paras=[
  # local-services-ads intro + "With Professional LSA Management"
  'Local Services Ads put your business at the very top of Google, above the pay-per-click ads and the organic results, with the Google Guarantee badge homeowners look for. You pay when a real customer contacts you directly, not for every click.',
  # local-services-ads "Google Guarantee" + "What's Included"
  'We take care of the Google Guarantee verification (background checks, plus license and insurance verification by Google), set up and optimize your profile, choose which services to advertise, watch lead quality and costs, and handle invalid lead disputes to protect your budget.'],
  more=('/marketing-services/local-services-ads/', 'More about Local Services Ads'))

# Ad channel descriptions. Google comes from ppc-advertising-services "What's Included";
# Meta and ChatGPT were written for these pages (approved by Orion, Oct 4 2026): general
# descriptions of the service only, no stats, cadences, minimums or guarantees.
AD_GOOGLE = 'pay-per-click campaigns built for home service searches, so your ads show up when homeowners search Google for the work you do. That includes market and competitor research, custom landing pages, call tracking, and reporting that connects your ads to booked jobs.'
AD_META = 'Facebook and Instagram ads targeted to homeowners in your service area. We create the ad creative and manage the campaigns, so your business stays in front of local homeowners on the apps they use every day.'
AD_CHATGPT = 'ads placed in ChatGPT conversations, so your business shows up when homeowners ask AI to help them find a contractor. We set up and manage the campaigns around the services you offer and the area you serve.'
# terms-and-conditions 3.1 "Third-Party Platform Costs"
AD_SPEND = 'Ad spend is separate from your program fee: you pay the ad platforms directly or reimburse us.'

def inc_channels(n):
    """Spark/Expand: one wide card describing the 3 channels to choose from.
    Conquer: one card per channel, since all 3 are included (matches its pricing card)."""
    more = ('/marketing-services/ppc-advertising-services/', 'More about pay-per-click ads')
    if n == 3:
        return [
          dict(icon='ads_click', title='Google ads', channel=True, more=more, paras=['Pay-per-click ' + AD_GOOGLE.split(' ', 1)[1]]),
          dict(icon='share', title='Meta ads (Facebook and Instagram)', channel=True, paras=[AD_META]),
          dict(icon='smart_toy', title='ChatGPT ads', channel=True, wide=True, paras=['Ads ' + AD_CHATGPT.split(' ', 1)[1]]),
        ]
    first = {1: 'Spark includes one paid ad channel, and you pick it: Google, Meta or ChatGPT.',
             2: 'Expand includes two paid ad channels, and you pick them from Google, Meta and ChatGPT.'}[n]
    title = {1: '1 ad channel of your choice', 2: '2 ad channels of your choice'}[n]
    paras = [first] + [f'<strong>{k}:</strong> {v}' for k, v in (('Google', AD_GOOGLE), ('Meta', AD_META), ('ChatGPT', AD_CHATGPT))] + \
            [AD_SPEND + ' Not sure which to choose? Book a call and we&#8217;ll talk it through.']
    return [dict(icon='ads_click', title=title, paras=paras, channel=True, wide=True, more=more)]

INC_GBP = dict(icon='pin_drop', title='Google Business Profile management', paras=[
  # local-seo-services "Why Local SEO"
  'Your Google Business Profile is what homeowners see in Google Maps and the Map Pack when they search for a contractor near them. When homeowners need home services they turn to Google first, and the contractor who shows up in the Map Pack gets the call.',
  # local-seo-services FAQ 02 (NAP consistency is a Local SEO ranking signal)
  'We manage your profile for you. Consistent business information, meaning your name, address and phone number, is one of the signals Google uses for local rankings.'])
INC_REVIEW = dict(icon='fact_check', title='Light website review', paras=[
  # local-seo-services FAQ 02
  'Homeowners who find you on Maps click through to your website, and if they land on a slow, confusing or outdated page, they leave. Service area pages, schema markup, consistent business information and page speed all affect how you rank in the Map Pack, which is why the plan includes a light review of your current site.'])
INC_UPDATES = dict(icon='edit_note', title='Light website updates', paras=[
  # marketing-programs Local SEO card
  'The plan includes light updates to your existing website. Website rebuilds and custom development are quoted separately.',
  # marketing-programs growth cards
  'If you need a new site, every growth program includes custom website design.'],
  more=('/marketing-services/website-design-services/', 'More about website design'))

def included(key):
    if key == 'local-seo': return [INC_GBP, INC_REVIEW, INC_UPDATES]
    return [INC_WEBSITE, INC_SEO, INC_REP, INC_LSA] + inc_channels(PROGRAMS[key]['channels'])

def annual_answer(p):
    return (f'Pay the year up front and you save 10%: {p["yr_total"]} for the year, which works out to {p["yr_month"]} a month. '
            'You also get a 12-month plan with the heavy lifting done up front. A prepaid year can&#8217;t be cancelled during that year. '
            'It renews yearly, so to stop it renewing, give 30 days&#8217; written notice before the renewal date.')
CONTRACT_Q = ('Is there a long-term contract?',
              'No. Every plan is month-to-month, and you can cancel any time with 30 days&#8217; written notice.')

def faqs(key):
    p = PROGRAMS[key]
    if key == 'local-seo':
        return [
          ('What&#8217;s included in the $350/month Local SEO plan?',
           'Google Business Profile management, a light website review and light website updates. Website rebuilds and custom development are quoted separately.'),
          CONTRACT_Q,
          ('How does the annual plan work?', annual_answer(p)),
          ('What if my website needs a rebuild?',
           'Website rebuilds and custom development are quoted separately. If you want a new site plus full marketing, every growth program, from $2,500/month, includes custom website design.'),
          ('How is Local SEO different from a growth program?',
           'Local SEO covers your Google Business Profile plus light website care. The growth programs, Spark, Expand and Conquer, add a custom website, search engine optimization, reputation management, Google Local Services Ads and 1 to 3 paid ad channels.'),
        ]
    ch = {1: ('Which ad channel can I choose with Spark?',
              'One of Google, Meta or ChatGPT. Expand includes 2 ad channels of your choice, and Conquer includes all 3.'),
          2: ('Which ad channels can I choose with Expand?',
              'Any 2 of Google, Meta and ChatGPT. Spark includes 1 ad channel of your choice, and Conquer includes all 3.'),
          3: ('Which ad channels does Conquer include?',
              'All 3: Google, Meta and ChatGPT. Spark includes 1 ad channel of your choice, and Expand includes 2.')}[p['channels']]
    spots = p['spots'].lower().replace('spots', 'spots').replace('available', 'available')
    return [
      ch,
      ('Is ad spend included in the program price?',
       'No. Advertising spend, including Google Local Services Ads, is separate from the program fee. You pay the ad platforms directly or reimburse us.'),
      CONTRACT_Q,
      ('How does the annual plan work?', annual_answer(p)),
      ('Why are spots limited?',
       f'We keep market exclusivity: one contractor per industry per service area. We also cap our client roster so every account gets our full attention. {p["short"]} has {spots}.'),
    ]

# ------------------------------------------------------------------ helpers
def ic(name, extra=''): return f'<span class="material-symbols-outlined{extra}" aria-hidden="true" data-icon="{name}"></span>'
def strip(x): return html.unescape(re.sub(r'<[^>]+>', '', x))
def attr(x): return html.escape(strip(x), quote=True)
ARROW = ic('arrow_forward').replace('<span ', '<span style="font-size:18px" ', 1)

def start_btn(key, label="Let&#8217;s Get Started"):
    return f'<a class="btn-cta" href="/schedule/" data-checkout="{key}" data-period="monthly">{label} {ARROW}</a>'

def panel(key):
    p = PROGRAMS[key]
    if key == 'local-seo':
        items = ['Google Business Profile Management', 'Light Website Review', 'Light Website Updates']
        lis = ''.join(f'<li>{ic("check_circle")}{t}</li>' for t in items)
    else:
        lis = ''.join(f'<li>{ic("check_circle")}{t}</li>' for t in GROWTH_LIST)
        lis += f'<li class="pp-channel">{ic("check_circle")}{CHANNEL_LABEL[p["channels"]]}</li>'
    badge = '<div class="pp-badge">Most Popular</div>' if p['featured'] else ''
    spots = f'<div class="pp-spots">{p["spots"]}</div>' if p['spots'] else ''
    return f'''<aside class="pp-panel{' featured' if p['featured'] else ''}" aria-label="{attr(p['name'])} at a glance">
      {badge}<div class="pp-panel-body">
        <div class="pp-panel-name">{p['name']}</div>
        <div class="pp-price"><span class="amount">{p['price']}</span><span class="per">/month</span></div>
        <ul class="pp-panel-list">{lis}</ul>
        {spots}
      </div>
    </aside>'''

def compare(cur):
    cols = ORDER
    def head(k):
        p = PROGRAMS[k]; c = ' class="is-current"' if k == cur else ''
        a = ' aria-current="page"' if k == cur else ''
        return f'<th scope="col"{c}><a href="/marketing-programs/{k}/"{a}>{p["name"]}</a></th>'
    yes = f'{ic("check_circle", " pp-yes")}<span class="pp-sr">Included</span>'
    no = '<span class="pp-no">Not included</span>'
    rows = [
      ('Monthly price', {k: f'<span class="pp-price-cell">{PROGRAMS[k]["mo"]}</span>' for k in cols}),
      ('Pay the year up front (save 10%)', {k: PROGRAMS[k]['yr'] for k in cols}),
      ('Google Business Profile', {'local-seo': 'Managed for you', 'spark': 'Optimized as part of SEO', 'expand': 'Optimized as part of SEO', 'conquer': 'Optimized as part of SEO'}),
      ('Website', {'local-seo': 'Light review and light updates', 'spark': 'Custom website design', 'expand': 'Custom website design', 'conquer': 'Custom website design'}),
      ('Search engine optimization', {'local-seo': no, 'spark': yes, 'expand': yes, 'conquer': yes}),
      ('Reputation management', {'local-seo': no, 'spark': yes, 'expand': yes, 'conquer': yes}),
      ('Google Local Services Ads', {'local-seo': no, 'spark': yes, 'expand': yes, 'conquer': yes}),
      ('Paid ad channels (Google, Meta, ChatGPT)', {'local-seo': no, 'spark': '1 of your choice', 'expand': '2 of your choice', 'conquer': 'All 3'}),
    ]
    body = ''
    for label, cells in rows:
        tds = ''.join(f'<td{" class=\"is-current\"" if k == cur else ""}>{cells[k]}</td>' for k in cols)
        body += f'<tr><th scope="row">{label}</th>{tds}</tr>\n'
    links = ''.join(
        f'<td class="is-current"><span class="pp-here">You are here</span></td>' if k == cur else
        f'<td><a href="/marketing-programs/{k}/">View {PROGRAMS[k]["short"]}</a></td>' for k in cols)
    body += f'<tr><th scope="row">Details</th>{links}</tr>\n'
    return f'''<p class="pp-compare-hint">Swipe sideways to see all 4 programs.</p>
<div class="pp-compare-scroll" role="region" aria-label="Compare programs" tabindex="0">
    <table class="pp-compare">
      <thead><tr><th scope="col"><span class="pp-sr">Feature</span></th>{''.join(head(k) for k in cols)}</tr></thead>
      <tbody>
{body}      </tbody>
    </table>
  </div>'''

def schema(key, url, faq):
    p, pg = PROGRAMS[key], PAGES[key]
    m, y, plus = p['offer']
    def offer(name, amount, unit, dur):
        spec = {'@type': 'UnitPriceSpecification', 'priceCurrency': 'USD', 'unitText': unit, 'billingDuration': dur}
        o = {'@type': 'Offer', 'name': name, 'priceCurrency': 'USD', 'url': url}
        if plus: spec['minPrice'] = str(amount)
        else: spec['price'] = str(amount); o['price'] = str(amount)
        o['priceSpecification'] = spec
        return o
    graph = [
      {'@type': 'BreadcrumbList', 'itemListElement': [
        {'@type': 'ListItem', 'position': 1, 'name': 'Home', 'item': ORIGIN + '/'},
        {'@type': 'ListItem', 'position': 2, 'name': 'Programs & Pricing', 'item': ORIGIN + '/marketing-programs/'},
        {'@type': 'ListItem', 'position': 3, 'name': p['name'], 'item': url}]},
      {'@type': 'Service', '@id': url + '#service', 'name': p['name'], 'url': url,
       'serviceType': 'Home service digital marketing', 'description': strip(pg['summary']),
       'audience': {'@type': 'BusinessAudience', 'name': 'Home service contractors'},
       'areaServed': {'@type': 'Country', 'name': 'United States'},
       'provider': {'@type': 'ProfessionalService', '@id': ORIGIN + '/#organization', 'name': BRAND, 'url': ORIGIN + '/',
                    'telephone': '+18336951214', 'email': 'team@outworkemdigital.com',
                    'logo': ORIGIN + '/img/outworkem-digital-logo-light-bg.webp',
                    'image': ORIGIN + '/img/og-default.jpg',
                    'address': {'@type': 'PostalAddress', 'streetAddress': '2425 E Camelback Road, Suite 150',
                                'addressLocality': 'Phoenix', 'addressRegion': 'AZ', 'postalCode': '85016', 'addressCountry': 'US'}},
       'offers': [offer('Monthly', m, 'month', 'P1M'), offer('Annual plan, paid up front (10% off)', y, 'year', 'P1Y')]},
      {'@type': 'FAQPage', 'mainEntity': [
        {'@type': 'Question', 'name': strip(q), 'acceptedAnswer': {'@type': 'Answer', 'text': strip(a)}} for q, a in faq]},
    ]
    return json.dumps({'@context': 'https://schema.org', '@graph': graph}, indent=1, ensure_ascii=False).replace('</', '<\\/')


# ------------------------------------------------------------------ Local SEO: extra sections
# Copy pulled from the former Local SEO service page (now redirected here, Oct 4 2026), restyled with the
# program-page components. Results stats, lead counts, cost-per-lead figures, timelines and
# guarantees on that page are deliberately left out.
LSEO_WHY_WITHOUT = ['Missing out on &#8220;near me&#8221; searches and emergency calls',
  'Competitors dominating the Google Map Pack in your area',
  'Losing leads to big companies with massive marketing budgets',
  'Website not showing up for nearby service searches',
  'Phone not ringing despite great service and reputation']
LSEO_WHY_WITH = ['Show up in the Google Map Pack when homeowners search',
  'Lock down your service area and block out competitors',
  'Generate consistent quality leads without massive ad spend',
  'Build a strong local reputation that brings referrals',
  'Turn your website into a 24/7 lead generation machine']
LSEO_WAYS = [  # "5 Ways Local SEO Drives Revenue" (stat / ranking-promise bullets removed)
  ('visibility', 'Increased Local Visibility', ['Dominate &#8220;near me&#8221; searches in your service area', 'Show up when homeowners need emergency service']),
  ('verified', 'Higher Quality Leads', ['Pre-qualified leads already in your service area', 'Homeowners actively searching for your services']),
  ('savings', 'Better ROI', ['Build long-term organic presence', 'Reduce dependency on expensive paid advertising']),
  ('travel_explore', 'Extended Market Reach', ['Rank for multiple service areas and neighborhoods', 'Capture searches across all your service offerings', 'Generate leads even in slower seasons']),
  ('workspace_premium', 'Stronger Brand Authority', ['Build trust through verified reviews and local presence', 'Showcase your expertise and track record', 'Position yourself as the go-to contractor locally']),
]
LSEO_GROWTH = [  # "Our Comprehensive Growth Programs" (Content Marketing row left out: it carries a volume figure)
  ('web', 'Home Service Website Foundation', [
    ('Homepage Design', 'Elevator pitch that builds trust and converts visitors into leads'),
    ('Service Pages', 'Ranks for profitable keywords and drives qualified visitors'),
    ('Service Area Pages', 'Rank for hyper-local searches and improve map 3-pack rankings'),
    ('About &amp; Team Pages', 'Build trust and authority, enhance conversion rate')]),
  ('tune', 'Marketing &amp; Optimization', [
    ('SEO 2.0', 'Generate organic leads consistently month over month'),
    ('Local SEO', 'Dominate &#8220;near me&#8221; searches &amp; Google local map pack'),
    ('Reputation Mgmt', 'Grow, answer, and display reviews on autopilot'),
    ('Listing Management', 'Improve local trust &amp; ranking signals across platforms'),
    ('Speed-to-Lead', 'Maximize conversion rates by being first to respond')]),
  ('monitoring', 'Tracking &amp; Reporting', [
    ('ROI Dashboard', 'Track your exact return on investment monthly'),
    ('Call Tracking', 'Monitor lead flow and attribution by channel'),
    ('Performance Reviews', 'Monthly strategy calls with your dedicated team'),
    ('Quarterly Review', 'Review of results and preview of next-quarter steps')]),
]
LSEO_APPROACH = [
  'While others chase volume, we prioritize quality partnerships that align with our values and vision. Just as you carefully select the brands and equipment you install for homeowners, we selectively choose the home service companies we partner with.',
  'This isn&#8217;t about being exclusive. It&#8217;s about ensuring maximum results through genuine collaboration. We maintain market exclusivity by accepting only one home service company per industry per service area. When we commit to your market, we commit fully.',
  'Our most successful client relationships share specific characteristics: open, honest communication; aligned business philosophy; shared personal values; a long-term growth mindset; and positive, energetic collaboration.']
LSEO_FIT = ['Committed to excellent customer service', 'Focused on sustainable, long-term growth',
  'Aware that Rome was not built in a day', 'Ready to play the long game', 'Looking to reduce paid advertising dependency']
LSEO_NOFIT = ['Looking for quick, temporary fixes', 'Without a growth mindset', 'Satisfied with the status quo',
  'Short-term focused in your operations']
LSEO_FAQ_MORE = [  # old page FAQs 01, 02, 04; 03 (lead counts / cost per lead) left out
  ('How long until I see results from Local SEO?',
   'Unlike paid advertising that delivers instant results, Local SEO is a long-term strategy. It builds lasting authority that delivers leads long-term.'),
  ('Do I need a new website for Local SEO?',
   'No. The Local SEO plan works with your current site. A strong site can still amplify your Map Pack results. Service area pages, schema markup and page speed all help you rank. Our growth programs (Spark, Expand and Conquer) include a custom website.'),
  ('Do you guarantee rankings or results?',
   'No ethical agency can guarantee specific rankings: Google&#8217;s algorithm is outside anyone&#8217;s control, and anyone promising a specific Map Pack position is not being straight with you.'),
]

def _list(items, icon, cls='pp-list'):
    return f'<ul class="{cls}">' + ''.join(f'<li>{ic(icon)}<span>{x}</span></li>' for x in items) + '</ul>'

def _acc(items, start, prefix='faq'):
    out = ''
    for n, (q, a) in enumerate(items, start):
        out += f"""    <div class="acc-item">
      <button class="acc-trigger" aria-expanded="false" aria-controls="{prefix}-{n}" id="{prefix}-q{n}">
        <span class="acc-n">{n:02d}</span>
        <span class="acc-head">{q}</span>
        {ic('expand_more', ' acc-icon')}
      </button>
      <div class="acc-body" id="{prefix}-{n}" role="region" aria-labelledby="{prefix}-q{n}"><div class="acc-inner"><p>{a}</p></div></div>
    </div>
"""
    return out

def lseo_extra(faq_start):
    ways = ''.join(f"""    <article class="pp-inc{' pp-wide' if i == len(LSEO_WAYS) - 1 else ''}">
      <div class="pp-inc-ic">{ic(icon)}</div>
      <h3>{t}</h3>
      {_list(items, 'check_circle')}
    </article>
""" for i, (icon, t, items) in enumerate(LSEO_WAYS))
    growth = ''.join(f"""    <article class="pp-inc">
      <div class="pp-inc-ic">{ic(icon)}</div>
      <h3>{t}</h3>
      <ul class="pp-deflist">{''.join(f'<li><strong>{a}</strong><span>{b}</span></li>' for a, b in rows)}</ul>
    </article>
""" for icon, t, rows in LSEO_GROWTH)
    prog_links = ''.join(f'<a class="pp-inc-more" href="/marketing-programs/{k}/">View {PROGRAMS[k]["short"]} {ic("arrow_forward")}</a>' for k in ('spark', 'expand', 'conquer'))
    return f"""
<!-- 8 · WHY LOCAL SEO (copy from the former Local SEO service page) -->
<section class="pp-section wrap" aria-labelledby="why-h">
  <div class="section-head center">
    <div class="kicker" style="justify-content:center"><span class="label">Why Local SEO</span></div>
    <h2 id="why-h">Why Local SEO Matters for Your Home Service Business</h2>
    <p class="lead">The contractor who shows up in the Map Pack gets the call. The one who doesn&#8217;t, doesn&#8217;t.</p>
  </div>
  <div class="pp-inc-grid">
    <article class="pp-inc">
      <div class="pp-inc-ic">{ic('search_off')}</div>
      <h3>Without Local SEO</h3>
      {_list(LSEO_WHY_WITHOUT, 'cancel', 'pp-list pp-list-no')}
    </article>
    <article class="pp-inc pp-channel">
      <div class="pp-inc-ic">{ic('task_alt')}</div>
      <h3>With Professional Local SEO</h3>
      {_list(LSEO_WHY_WITH, 'check_circle')}
    </article>
  </div>
</section>

<!-- 9 · HOW LOCAL SEO DRIVES REVENUE -->
<section class="pp-section wrap band" aria-labelledby="ways-h">
  <div class="section-head center">
    <div class="kicker" style="justify-content:center"><span class="label">5 Ways Local SEO Drives Revenue</span></div>
    <h2 id="ways-h">How Local SEO Turns Your Service Area Into a Lead Pipeline</h2>
    <p class="lead">When homeowners in your area need home services, you&#8217;ll be the first name they see, exactly when and where they&#8217;re searching.</p>
  </div>
  <div class="pp-inc-grid">
{ways}  </div>
</section>

<!-- 10 · GROWTH PROGRAMS -->
<section class="pp-section wrap" aria-labelledby="growth-h">
  <div class="section-head center">
    <div class="kicker" style="justify-content:center"><span class="label">Growth Programs</span></div>
    <h2 id="growth-h">Want More Than Local SEO on Its Own?</h2>
    <p class="lead">Effective digital marketing works best with all components working together as one integrated system, and that&#8217;s what our growth programs deliver.</p>
  </div>
  <div class="pp-inc-grid pp-grid-3">
{growth}  </div>
  <div class="pp-prog-links">{prog_links}</div>
</section>

<!-- 11 · OUR APPROACH -->
<section class="pp-section wrap band" aria-labelledby="approach-h">
  <div class="pp-billing">
    <div class="section-head" style="margin-bottom:0">
      <div class="kicker"><span class="label">Working with Outwork&#8217;em Digital</span><span class="rule"></span></div>
      <h2 id="approach-h">We Take a Different Approach Than Most Agencies</h2>
      {''.join(f'<p class="pp-prose">{x}</p>' for x in LSEO_APPROACH)}
    </div>
    <div class="pp-fit">
      <article class="pp-inc pp-channel">
        <div class="pp-inc-ic">{ic('handshake')}</div>
        <h3>We Are a Good Fit If You Are:</h3>
        {_list(LSEO_FIT, 'check_circle')}
      </article>
      <article class="pp-inc">
        <div class="pp-inc-ic">{ic('block')}</div>
        <h3>We Are Not a Good Fit If You Are:</h3>
        {_list(LSEO_NOFIT, 'cancel', 'pp-list pp-list-no')}
      </article>
    </div>
  </div>
</section>

<!-- 12 · MORE FAQ -->
<section class="faq-section wrap" aria-labelledby="faq2-h">
  <div class="section-head center">
    <div class="kicker" style="justify-content:center"><span class="label">More Questions</span></div>
    <h2 id="faq2-h">More Straight Answers About Local SEO</h2>
  </div>
  <div class="accordion">
{_acc(LSEO_FAQ_MORE, faq_start)}  </div>
</section>
"""

# ------------------------------------------------------------------ layout
def page(key):
    p, pg = PROGRAMS[key], PAGES[key]
    url = f'{ORIGIN}/marketing-programs/{key}/'
    growth = key != 'local-seo'
    faq = faqs(key)
    faq_all = list(faq)
    if key == 'local-seo':
        seen = {strip(q).lower() for q, _ in faq}
        faq_all += [x for x in LSEO_FAQ_MORE if strip(x[0]).lower() not in seen]
    extra = lseo_extra(len(faq) + 1) if key == 'local-seo' else ''
    inc = ''
    for it in included(key):
        paras = ''.join(f'<p>{x}</p>' for x in it['paras'])
        more = f'<a class="pp-inc-more" href="{it["more"][0]}">{it["more"][1]} {ic("arrow_forward")}</a>' if it.get('more') else ''
        inc += f'''    <article class="pp-inc{' pp-channel' if it.get('channel') else ''}{' pp-wide' if it.get('wide') else ''}">
      <div class="pp-inc-ic">{ic(it['icon'])}</div>
      <h3>{it['title']}</h3>
      {paras}
      {more}
    </article>
'''
    inc_note = f'<p class="pp-inc-note">{AD_SPEND}</p>' if p.get('channels') == 3 else ''
    billing = [
      ('event_available', 'Month-to-month.', 'Every plan is month-to-month. Cancel any time with 30 days&#8217; written notice.'),
      ('calendar_month', 'Prepaid year.', 'If you pay the year up front, that year can&#8217;t be cancelled. It renews yearly; to stop it renewing, give 30 days&#8217; written notice before the renewal date.'),
    ]
    if growth:
        billing.append(('campaign', 'Ad spend.', 'Advertising spend isn&#8217;t part of the program fee. You pay the ad platforms directly or reimburse us.'))
    bl = ''.join(f'<li>{ic(i)}<span><strong>{t}</strong> {d}</span></li>' for i, t, d in billing)
    acc = ''
    for n, (q, a) in enumerate(faq, 1):
        acc += f'''    <div class="acc-item">
      <button class="acc-trigger" aria-expanded="false" aria-controls="faq-{n}" id="faq-q{n}">
        <span class="acc-n">{n:02d}</span>
        <span class="acc-head">{q}</span>
        {ic('expand_more', ' acc-icon')}
      </button>
      <div class="acc-body" id="faq-{n}" role="region" aria-labelledby="faq-q{n}"><div class="acc-inner"><p>{a}</p></div></div>
    </div>
'''
    return f'''<!DOCTYPE html>
<html lang="en" data-theme="dark">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
{ANALYTICS}
<title>{html.escape(pg['title'], quote=False)}</title>
<meta name="description" content="{attr(pg['desc'])}">
<link rel="canonical" href="{url}">
<meta property="og:type" content="website">
<meta property="og:site_name" content="Outwork&#39;em Digital">
<meta property="og:url" content="{url}">
<meta property="og:title" content="{attr(pg['title'])}">
<meta property="og:description" content="{attr(pg['desc'])}">
<meta property="og:image" content="{ORIGIN}/img/og-default.jpg">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="{attr(pg['title'])}">
<meta name="twitter:description" content="{attr(pg['desc'])}">
<meta name="twitter:image" content="{ORIGIN}/img/og-default.jpg">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
{FONTS}
<link rel="stylesheet" href="/css/service.718350f55c.css">
<link rel="stylesheet" href="{CSS_HREF}">
{THEME}
<script type="application/ld+json">
{schema(key, url, faq_all)}
</script>
{ICONS}
</head>
<body>
<!-- Generated by _src/program-pages/build.py (shared program-page layout). Edit the source, then rebuild. -->
{BODY_TOP}<main id="main">

<!-- 1 · HERO -->
<section class="pp-hero wrap">
  <nav class="pp-crumbs" aria-label="Breadcrumb"><ol>
    <li><a href="/">Home</a></li><li><a href="/marketing-programs/">Programs &amp; Pricing</a></li><li><span aria-current="page">{p['name']}</span></li>
  </ol></nav>
  <div class="pp-hero-grid">
    <div>
      <div class="svc-chip">{ic('rocket_launch' if growth else 'pin_drop')}{p['kind']}</div>
      <h1>{pg['h1']}</h1>
      <p class="pp-summary">{pg['summary']}</p>
      <div class="pp-actions">
        {start_btn(key)}
        <a class="pp-book" href="/schedule/">Questions? Book a call</a>
      </div>
      <p class="pp-hero-terms">{p['price']}/month &middot; Month-to-month &middot; 30 days&#8217; notice to cancel</p>
    </div>
    {panel(key)}
  </div>
</section>

<!-- 2 · WHAT'S INCLUDED -->
<section class="pp-section wrap band" aria-labelledby="inc-h">
  <div class="section-head center">
    <div class="kicker" style="justify-content:center"><span class="label">What&#8217;s Included</span></div>
    <h2 id="inc-h">What&#8217;s Included in {p['name']}</h2>
    <p class="lead">Here&#8217;s what each part of the {'plan' if not growth else 'program'} covers.</p>
  </div>
  <div class="pp-inc-grid">
{inc}  </div>
  {inc_note}
</section>

<!-- 3 · ANNUAL PLAN -->
<section class="pp-section wrap" aria-labelledby="annual-h">
  <div class="pp-annual">
    <div>
      <div class="kicker"><span class="label">Annual Plan</span><span class="rule"></span></div>
      <h2 id="annual-h">Prefer to Pay for the Year?</h2>
      <p class="pp-annual-copy">Pay the year up front: save 10% and get a 12-month plan with the heavy lifting done up front.</p>
    </div>
    <div class="pp-annual-side">
      <div class="pp-annual-total">{p['yr']}</div>
      <div class="pp-annual-mo">({p['yr_mo']})</div>
      <div data-checkout-wrap hidden><a class="btn-cta" href="/schedule/" data-checkout="{key}" data-period="yearly">Pay yearly {ARROW}</a></div>
      <p class="pp-annual-renew">Prepaid years renew yearly; 30 days&#8217; notice before renewal.</p>
    </div>
  </div>
</section>

<!-- 4 · HOW BILLING WORKS -->
<section class="pp-section wrap band" aria-labelledby="billing-h">
  <div class="pp-billing">
    <div class="section-head" style="margin-bottom:0">
      <div class="kicker"><span class="label">Billing</span><span class="rule"></span></div>
      <h2 id="billing-h">How Billing Works</h2>
      <p class="lead">No long-term contract. Here&#8217;s how paying for {p['name']} works.</p>
    </div>
    <div>
      <ul class="pp-billing-list">{bl}</ul>
      <a class="pp-terms-link" href="/terms-and-conditions/#10-term-renewal-and-termination"><span>Read the full terms</span> {ic('arrow_forward')}</a>
    </div>
  </div>
</section>

<!-- 5 · FAQ -->
<section class="faq-section wrap" aria-labelledby="faq-h">
  <div class="section-head center">
    <div class="kicker" style="justify-content:center"><span class="label">Frequently Asked Questions</span></div>
    <h2 id="faq-h">Straight Answers About {p['name']}</h2>
  </div>
  <div class="accordion">
{acc}  </div>
</section>

<!-- 6 · COMPARE PROGRAMS -->
<section class="pp-section wrap band" aria-labelledby="compare-h">
  <div class="section-head center">
    <div class="kicker" style="justify-content:center"><span class="label">Compare Programs</span></div>
    <h2 id="compare-h">Compare All 4 Programs</h2>
    <p class="lead">See how {p['name']} stacks up against the other plans.</p>
  </div>
  {compare(key)}
  <p class="pp-compare-note">Every plan is month-to-month with 30 days&#8217; notice to cancel. <a href="/marketing-programs/">See all pricing</a></p>
</section>

{extra}
<!-- 7 · CLOSING CTA -->
<section class="final-cta wrap">
  <div class="cta-band">
    <h2>Ready to Get Started With {p['name']}?</h2>
    <p>Start online today, or book a call if you&#8217;d like to talk it through first. You can also call <a href="tel:8336951214" style="color:inherit;text-decoration:none">833-695-1214</a>.</p>
    <div class="pp-cta-actions">
      {start_btn(key)}
      <a class="pp-book" href="/schedule/">Questions? Book a call</a>
    </div>
  </div>
</section>

</main>
{FOOTER}

<script src="/js/program-checkout.js" defer></script>
{open(os.path.join(SRC, 'page.js')).read()}
</body>
</html>
'''

for k in ORDER:
    out = os.path.join(ROOT, 'marketing-programs', k, 'index.html')
    os.makedirs(os.path.dirname(out), exist_ok=True)
    open(out, 'w', encoding='utf-8').write(page(k))
    print('wrote', os.path.relpath(out, ROOT))
print('wrote', CSS_HREF)
